[ "$LXC_DOCKER" ] && CONFIGS_ON+="
CONFIG_SYSVIPC
CONFIG_POSIX_MQUEUE
CONFIG_CGROUP_DEVICE
CONFIG_PID_NS
CONFIG_USER_NS
CONFIG_NETFILTER_XT_TARGET_CHECKSUM
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE
CONFIG_IP6_NF_NAT
CONFIG_IP6_NF_TARGET_MASQUERADE
CONFIG_BT_HCIVHCI
CONFIG_DEVTMPFS
CONFIG_VT
CONFIG_NULL_TTY
" && CONFIGS_OFF+="
"